version: "3"

services: 
  db:
    image: postgres
    restart: "always"
    expose:
      - "5433"
    ports:
      - "5433:5433"
    
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: budgetApp
    volumes: 
      - "./db:/var/lib/postgresql/data"